Mimic.copy(AnnotAt.Atproto.DNS)
Mimic.copy(AnnotAt.Atproto.Directory)
Mimic.copy(AnnotAt.Atproto.HTTP)
Mimic.copy(AnnotAt.Atproto.Profile)
Mimic.copy(AnnotAt.Atproto.StandardSite)
Mimic.copy(AnnotAt.Feeds.Client)
Mimic.copy(AnnotAt.Login)
Mimic.copy(Latch)

ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(AnnotAt.Repo, :manual)
